import { resolve } from 'node:path'
import { defineConfig } from 'vitest/config'
import viteTsConfigPaths from 'vite-tsconfig-paths'

const srcPath = (path: string) =>
  resolve(__dirname, 'src', path).replace(/\\/g, '/')

export default defineConfig({
  plugins: [
    viteTsConfigPaths({
      projects: ['./tsconfig.json'],
    }),
  ],
  resolve: {
    alias: [
      { find: '@/components/AetherLogo', replacement: srcPath('shared/components/AetherLogo.tsx') },
      { find: '@/components/ImagePreview', replacement: srcPath('shared/components/ImagePreview.tsx') },
      { find: '@/components/Markdown', replacement: srcPath('shared/components/Markdown.tsx') },
      { find: '@/components/MarkdownImpl', replacement: srcPath('shared/components/MarkdownImpl.tsx') },
      { find: '@/components/ResponsiveContext', replacement: srcPath('shared/providers/ResponsiveContext.tsx') },
      { find: /^@\/components\/ai-elements\/(.*)$/, replacement: `${srcPath('shared/components/ai-elements')}/$1` },
      { find: /^@\/components\/chat\/share\/(.*)$/, replacement: `${srcPath('features/share/components')}/$1` },
      { find: /^@\/components\/chat\/(.*)$/, replacement: `${srcPath('features/chat/components')}/$1` },
      { find: '@/components/ChatRoom', replacement: srcPath('features/chat/components/ChatRoom.tsx') },
      { find: '@/components/sidebar/NotesButton', replacement: srcPath('features/notes/components/NotesButton.tsx') },
      { find: '@/components/sidebar/Sidebar', replacement: srcPath('features/shell/components/Sidebar.tsx') },
      { find: /^@\/components\/sidebar\/conversation\/(.*)$/, replacement: `${srcPath('features/conversations/components')}/$1` },
      { find: /^@\/components\/sidebar\/search\/(.*)$/, replacement: `${srcPath('features/conversations/components/search')}/$1` },
      { find: /^@\/components\/sidebar\/settings\/(.*)$/, replacement: `${srcPath('features/settings/components')}/$1` },
      { find: /^@\/components\/ui\/(.*)$/, replacement: `${srcPath('shared/ui')}/$1` },
      { find: /^@\/components\/notes\/(.*)$/, replacement: `${srcPath('features/notes/components')}/$1` },
      { find: '@/hooks/useTheme', replacement: srcPath('shared/hooks/useTheme.ts') },
      { find: '@/hooks/useToast', replacement: srcPath('shared/hooks/useToast.ts') },
      { find: '@/hooks/useViewportHeight', replacement: srcPath('shared/hooks/useViewportHeight.ts') },
      { find: '@/hooks/useConversationLoader', replacement: srcPath('features/conversations/hooks/useConversationLoader.ts') },
      { find: /^@\/lib\/auth\/(.*)$/, replacement: `${srcPath('features/auth/client')}/$1` },
      { find: /^@\/lib\/chat\/(.*)$/, replacement: `${srcPath('features/chat/lib')}/$1` },
      { find: /^@\/lib\/conversation\/(.*)$/, replacement: `${srcPath('features/conversations/lib')}/$1` },
      { find: /^@\/lib\/(.*)$/, replacement: `${srcPath('shared/lib')}/$1` },
      { find: /^@\/server\/agents\/(.*)$/, replacement: `${srcPath('features/chat/server/agents')}/$1` },
      { find: '@/server/base64', replacement: srcPath('shared/server/base64.ts') },
      { find: '@/server/db/conversation-shares-db', replacement: srcPath('features/share/server/conversation-shares-db.ts') },
      { find: '@/server/db/conversations-db', replacement: srcPath('features/conversations/server/conversations-db.ts') },
      { find: '@/server/db/notes-db', replacement: srcPath('features/notes/server/notes-db.ts') },
      { find: '@/server/db/prompt-quota-db', replacement: srcPath('features/quota/server/prompt-quota-db.ts') },
      { find: '@/server/env', replacement: srcPath('shared/server/env.ts') },
      { find: '@/server/functions/admin/redeem-codes', replacement: srcPath('features/quota/server/redeem-codes.ts') },
      { find: /^@\/server\/functions\/auth\/(.*)$/, replacement: `${srcPath('features/auth/server')}/$1` },
      { find: /^@\/server\/functions\/chat\/(.*)$/, replacement: `${srcPath('features/chat/server/functions')}/$1` },
      { find: '@/server/functions/conversations', replacement: srcPath('features/conversations/server/conversations.ts') },
      { find: '@/server/functions/notes', replacement: srcPath('features/notes/server/notes.ts') },
      { find: '@/server/functions/quota', replacement: srcPath('features/quota/server/quota.ts') },
      { find: '@/server/functions/shares', replacement: srcPath('features/share/server/shares.ts') },
      { find: '@/server/functions/theme', replacement: srcPath('shared/server/theme.ts') },
      { find: '@/server/functions/tts', replacement: srcPath('features/chat/server/functions/tts.ts') },
      { find: '@/stores/zustand/useChatRequestStore', replacement: srcPath('features/chat/store/useChatRequestStore.ts') },
      { find: '@/stores/zustand/useComposerStore', replacement: srcPath('features/chat/store/useComposerStore.ts') },
      { find: '@/stores/zustand/useConversationsStore', replacement: srcPath('features/conversations/store/useConversationsStore.ts') },
      { find: '@/stores/zustand/useEditingStore', replacement: srcPath('features/chat/store/useEditingStore.ts') },
      { find: '@/stores/zustand/useMessageTreeStore', replacement: srcPath('features/conversations/store/useMessageTreeStore.ts') },
      { find: '@/stores/zustand/useNotesStore', replacement: srcPath('features/notes/store/useNotesStore.ts') },
      { find: '@/stores/zustand/toast', replacement: srcPath('shared/stores/toast.ts') },
      { find: '@/types/chat-api', replacement: srcPath('features/chat/types/chat-api.ts') },
      { find: '@/types/chat-event-types', replacement: srcPath('features/chat/types/chat-event-types.ts') },
      { find: '@/types/conversation', replacement: srcPath('features/conversations/types/conversation.ts') },
      { find: '@/types/message', replacement: srcPath('features/chat/types/message.ts') },
      { find: '@/types/share', replacement: srcPath('features/share/types/share.ts') },
      { find: 'cloudflare:workers', replacement: srcPath('shared/test/mocks/cloudflare-workers.ts') },
      { find: '@', replacement: srcPath('') },
    ],
  },
  test: {
    environment: 'happy-dom',
    include: ['src/**/*.test.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      reportsDirectory: 'coverage',
    },
  },
})
