/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R404RouteImport } from './routes/404'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoteIndexRouteImport } from './routes/note/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as ApiUploadAttachmentRouteImport } from './routes/api/upload-attachment'
import { Route as ApiClientErrorsRouteImport } from './routes/api/client-errors'
import { Route as AppCConversationIdRouteImport } from './routes/app/c/$conversationId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAssetsKeyRouteImport } from './routes/api/assets/$key'
import { Route as ApiShareAssetsTokenAttachmentIdRouteImport } from './routes/api/share-assets/$token/$attachmentId'

const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteIndexRoute = NoteIndexRouteImport.update({
  id: '/note/',
  path: '/note/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiUploadAttachmentRoute = ApiUploadAttachmentRouteImport.update({
  id: '/api/upload-attachment',
  path: '/api/upload-attachment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientErrorsRoute = ApiClientErrorsRouteImport.update({
  id: '/api/client-errors',
  path: '/api/client-errors',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCConversationIdRoute = AppCConversationIdRouteImport.update({
  id: '/c/$conversationId',
  path: '/c/$conversationId',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsKeyRoute = ApiAssetsKeyRouteImport.update({
  id: '/api/assets/$key',
  path: '/api/assets/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareAssetsTokenAttachmentIdRoute =
  ApiShareAssetsTokenAttachmentIdRouteImport.update({
    id: '/api/share-assets/$token/$attachmentId',
    path: '/api/share-assets/$token/$attachmentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/404': typeof R404Route
  '/api/client-errors': typeof ApiClientErrorsRoute
  '/api/upload-attachment': typeof ApiUploadAttachmentRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/share/$token': typeof ShareTokenRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/note/': typeof NoteIndexRoute
  '/api/assets/$key': typeof ApiAssetsKeyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/c/$conversationId': typeof AppCConversationIdRoute
  '/api/share-assets/$token/$attachmentId': typeof ApiShareAssetsTokenAttachmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/api/client-errors': typeof ApiClientErrorsRoute
  '/api/upload-attachment': typeof ApiUploadAttachmentRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/share/$token': typeof ShareTokenRoute
  '/app': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/note': typeof NoteIndexRoute
  '/api/assets/$key': typeof ApiAssetsKeyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/c/$conversationId': typeof AppCConversationIdRoute
  '/api/share-assets/$token/$attachmentId': typeof ApiShareAssetsTokenAttachmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/404': typeof R404Route
  '/api/client-errors': typeof ApiClientErrorsRoute
  '/api/upload-attachment': typeof ApiUploadAttachmentRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/share/$token': typeof ShareTokenRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/note/': typeof NoteIndexRoute
  '/api/assets/$key': typeof ApiAssetsKeyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/c/$conversationId': typeof AppCConversationIdRoute
  '/api/share-assets/$token/$attachmentId': typeof ApiShareAssetsTokenAttachmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/404'
    | '/api/client-errors'
    | '/api/upload-attachment'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/share/$token'
    | '/app/'
    | '/auth/'
    | '/note/'
    | '/api/assets/$key'
    | '/api/auth/$'
    | '/app/c/$conversationId'
    | '/api/share-assets/$token/$attachmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/api/client-errors'
    | '/api/upload-attachment'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/share/$token'
    | '/app'
    | '/auth'
    | '/note'
    | '/api/assets/$key'
    | '/api/auth/$'
    | '/app/c/$conversationId'
    | '/api/share-assets/$token/$attachmentId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/404'
    | '/api/client-errors'
    | '/api/upload-attachment'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/share/$token'
    | '/app/'
    | '/auth/'
    | '/note/'
    | '/api/assets/$key'
    | '/api/auth/$'
    | '/app/c/$conversationId'
    | '/api/share-assets/$token/$attachmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  R404Route: typeof R404Route
  ApiClientErrorsRoute: typeof ApiClientErrorsRoute
  ApiUploadAttachmentRoute: typeof ApiUploadAttachmentRoute
  ShareTokenRoute: typeof ShareTokenRoute
  NoteIndexRoute: typeof NoteIndexRoute
  ApiAssetsKeyRoute: typeof ApiAssetsKeyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiShareAssetsTokenAttachmentIdRoute: typeof ApiShareAssetsTokenAttachmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/': {
      id: '/note/'
      path: '/note'
      fullPath: '/note/'
      preLoaderRoute: typeof NoteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/upload-attachment': {
      id: '/api/upload-attachment'
      path: '/api/upload-attachment'
      fullPath: '/api/upload-attachment'
      preLoaderRoute: typeof ApiUploadAttachmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/client-errors': {
      id: '/api/client-errors'
      path: '/api/client-errors'
      fullPath: '/api/client-errors'
      preLoaderRoute: typeof ApiClientErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/c/$conversationId': {
      id: '/app/c/$conversationId'
      path: '/c/$conversationId'
      fullPath: '/app/c/$conversationId'
      preLoaderRoute: typeof AppCConversationIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$key': {
      id: '/api/assets/$key'
      path: '/api/assets/$key'
      fullPath: '/api/assets/$key'
      preLoaderRoute: typeof ApiAssetsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share-assets/$token/$attachmentId': {
      id: '/api/share-assets/$token/$attachmentId'
      path: '/api/share-assets/$token/$attachmentId'
      fullPath: '/api/share-assets/$token/$attachmentId'
      preLoaderRoute: typeof ApiShareAssetsTokenAttachmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCConversationIdRoute: typeof AppCConversationIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCConversationIdRoute: AppCConversationIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  R404Route: R404Route,
  ApiClientErrorsRoute: ApiClientErrorsRoute,
  ApiUploadAttachmentRoute: ApiUploadAttachmentRoute,
  ShareTokenRoute: ShareTokenRoute,
  NoteIndexRoute: NoteIndexRoute,
  ApiAssetsKeyRoute: ApiAssetsKeyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiShareAssetsTokenAttachmentIdRoute: ApiShareAssetsTokenAttachmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
